language: java
jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11

matrix:
  include:
    - jdk: openjdk11
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
