name: Java 7
on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
      - name: Set up Azul JDK 7
        uses: actions/setup-java@v3
        with:
          java-version: 7
          distribution: 'zulu'
          cache: 'maven'
      - name: Test in Maven
        run: mvn test